add dependencies for firebase
dimagi/biometric-android pull request #13
Opened 2023-10-13 08:23 UTC by zandre-eng

Adds in necessary dependencies to integrate firebase crashlytics to the biometric application. The `google_services.json` file has been excluded and will need to be separately pulled in when setting up a developer environment.

2023-10-19 11:27 UTC, avazirna requested changes
@zandre-eng this looks fine, my only concern is about the distribution of the firebase configuration file. As part of this, can you maybe add some instructions on how to add it to the dev environment?

2023-10-19 11:43 UTC, zandre-eng commented
> this looks fine, my only concern is about the distribution of the firebase configuration file. As part of this, can you maybe add some instructions on how to add it to the dev environment?

I have added a section in the repo README for adding the firebase configuration file. Please let me know however, if you think this requires more detail.

2023-10-23 07:40 UTC, avazirna commented
> > this looks fine, my only concern is about the distribution of the firebase configuration file. As part of this, can you maybe add some instructions on how to add it to the dev environment?
> 
> @avazirna I have added a section in the repo README for adding the firebase configuration file. Please let me know however, if you think this requires more detail.

@zandre-eng I believe it's always better to PR documentation updates with the actual changes, it also helps to give additional context about the feature. My note here is whether we should make this an optional step but also if there any concerns with the approach (not adding the file to the project). It seems fine to me, given the stage of the project.

2023-10-23 08:09 UTC, avazirna approved these changes

2023-10-23 13:19 UTC, shubham1g5 commented
Think a better way to handle google_serivces.json is provide a template with apikey nulled out like in [cc android ](https://github.com/dimagi/commcare-android/blob/master/app/templates/google-services.json) and then [use a gradle task](https://github.com/dimagi/commcare-android/blob/master/app/build.gradle#L181) to inject the keys in a particular environment or CI. This way you can just add the api key to the local properties file in environment to have the firebase setup working.

2023-10-25 07:21 UTC, avazirna commented
> Think a better way to handle google_serivces.json is provide a template with apikey nulled out like in [cc android ](https://github.com/dimagi/commcare-android/blob/master/app/templates/google-services.json) and then [use a gradle task](https://github.com/dimagi/commcare-android/blob/master/app/build.gradle#L181) to inject the keys in a particular environment or CI. This way you can just add the api key to the local properties file in environment to have the firebase setup working.

Yeah, agreed. @zandre-eng I think we can merge this and address how we handle the Firebase config file on a separate PR.

2024-06-04 13:40 UTC, merged